apiVersion: batch/v1
kind: Job
metadata:
  name: your-job-name
spec:
  template:
    metadata:
      name: your-pod-name
    spec:
      containers:
      - name: your-container-name
        image: your-docker-image
        command: ["/bin/bash", "-c"]
        args:
        - |
          #!/bin/bash
          # Add your Bash commands here
          echo "Hello, World!"
      restartPolicy: Never
