apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "replaceAtWithRandom"}}
spec:
  template:
    metadata:
      name: vm-operations
    spec:
      containers:
      - name: vm-operations
        image: badal773/private:vm-operation-v1
        command: ["/bin/bash", "azure-operations.sh"]
        env:
          - name: EMAIL_ID
            values: {{ $.Values.email_id }}
          - name: WANT_TO_START
            values: {{ $.Values.WANT_TO_START  | quote}}
          - name: WANT_TO_STOP
            values: {{ $.Values.WANT_TO_STOP  | quote}}
          - name: WANT_TO_RESTART
            values: {{ $.Values.WANT_TO_RESTART | quote }}
          - name: WANT_TO_DELETE
            values: {{ $.Values.WANT_TO_DELETE  | quote}}
      restartPolicy: Never
      imagepullsecret: 
        - name: vm-operation
