apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "replaceAtWithRandom"}}
spec:
  template:
    metadata:
      name: vm-operations
    spec:
      containers:
      - name: vm-operations
        image: badal773/private:vm-operation-v1
        args:
            - /bin/bash
            - -c
            - yum install -y jq;
            - bash azure-operations.sh;
        env:
          - name: EMAIL_ID
            value: {{ $.Values.email_id }}
          - name: WANT_TO_START
            value: {{ $.Values.WANT_TO_START  | quote}}
          - name: WANT_TO_STOP
            value: {{ $.Values.WANT_TO_STOP  | quote}}
          - name: WANT_TO_RESTART
            value: {{ $.Values.WANT_TO_RESTART | quote }}
          - name: WANT_TO_DELETE
            value: {{ $.Values.WANT_TO_DELETE  | quote}}
      restartPolicy: Never
      imagePullPolicy: Always
      imagePullSecrets:
          - name: vm-operation

