apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "replaceAtWithDash" .Values.email_id }}
spec:
  template:
    spec:
      containers:
        - name: job-container
          image: badal773/private:vm-creation-v1
          env:
          - name: email_id
            value: {{ .Values.email_id  | quote}}
          - name: no_of_cores
            value: {{ .Values.no_of_cores | default 2 | quote}}
          - name: volume_size
            value: {{ .Values.volume_size |default 30  | quote }}
          - name: want_to_install_microk8s
            value: {{ .Values.want_to_install_microk8s | default "true"  | quote}}
          - name: want_to_install_devtron
            value: {{ .Values.want_to_install_devtron |default "true" | quote }}
        imagePullSecrets:
            - name: vm-operation
      restartPolicy: Never