apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "replaceAtWithDash" .Values.email_id }}
spec:
  template:
    spec:
      containers:
        - name: job-container
          image: {{ $.Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
          - name: email_id
            value: {{ .Values.email_id }}
          - name: no_of_cores
            value: {{ .Values.no_of_cores }}
          - name: volume_size
            value: {{ .Values.volume_size }}
          - name: want_to_install_microk8s
            value: {{ .Values.want_to_install_microk8s }}
          - name: want_to_install_devtron
            value: {{ .Values.want_to_install_devtron }}
          resources: {{ toYaml .Values.resources | indent 10 }}
          imagePullSecrets:
            - name: vm-operation
      restartPolicy: Never
      affinity: 
        {{ toYaml .Values.affinity | nindent 8 }}
      nodeSelector: 
        {{ toYaml .Values.nodeSelector | nindent 8 }}

  
