apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "replaceAtWithRandom" }} 
spec:
  template:
    spec:
      containers:
        - name: aws-cli
          image: badal773/route-53:v1
          command: ["bash", "rout53map.sh"]
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: HOSTED_ZONE_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: HOSTED_ZONE_ID
            - name: DOMAIN_NAME
              value: {{ $.Values.DOMAIN_NAME | quote }} 
            - name: IP_ADDRESS
              value: {{ $.Values.IP_ADDRESS  | quote }} 
            - name: A
              value: {{ $.Values.A |default "true"  | quote}}
            - name: CNAME
              value: {{ $.Values.CNAME | quote  }}
      restartPolicy: Never

